#!/usr/bin/env python3
"""coverage-matrix.py — per-family role coverage, the wave planner.

Emits docs/COVERAGE-MATRIX.md (generated, numbers-only-via-script) showing
for each AeroSkills family: leaves total, leaves bound, coverage %, roles
that bind it, and the top unbound sub-cluster candidates (next-wave).

Usage: python3 scripts/coverage-matrix.py [--check]
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "COVERAGE-MATRIX.md")

LEDGER = os.path.join(ROOT, "scripts", "binding-ledger.py")


def load_ledger() -> dict:
    r = subprocess.run([sys.executable, LEDGER, "--json"],
                       capture_output=True, text=True, cwd=ROOT)
    return json.loads(r.stdout)


def render(ledger: dict) -> str:
    fam = ledger["per_family"]
    lines = [
        "---",
        "type: doc",
        "title: Role coverage matrix (wave planner)",
        "status: generated",
        "created: 2026-09-05",
        "updated: 2026-09-05",
        "tags: [aero, roles, coverage, waves, growth]",
        "pipeline: generated",
        "---",
        "",
        "# Role coverage matrix",
        "",
        f"Generated by `scripts/coverage-matrix.py` from the binding ledger.",
        "",
        f"- Roles: **{ledger['roles']}**",
        f"- AeroSkills leaves: **{ledger['leaves_total']}**",
        f"- Leaves bound: **{ledger['leaves_bound']}** "
        f"({ledger['coverage_pct']}%)",
        f"- Unbound: **{ledger['unbound_leaves']}** (next-wave candidates)",
        "",
        "## Per family",
        "",
        "| Family | Leaves | Bound | Coverage | Next-wave clusters (unbound) |",
        "|---|---|---|---|---|",
    ]
    # group unbound by family for candidate listing
    from collections import Counter
    cand_by_fam: dict[str, Counter] = {}
    for leaf in ledger.get("role_ready_clusters", []):
        parts = leaf.split("/")
        if len(parts) >= 2:
            f = parts[0]
            cand_by_fam.setdefault(f, Counter())
            cand_by_fam[f]["/".join(parts[:2])] += 1
    for f in sorted(fam):
        st = fam[f]
        pct = (st["bound"] / st["leaves"] * 100.0) if st["leaves"] else 0
        cands = cand_by_fam.get(f, Counter())
        top = ", ".join(f"{k} ({v})" for k, v in cands.most_common(3))
        lines.append(f"| {f} | {st['leaves']} | {st['bound']} | "
                     f"{pct:.0f}% | {top} |")
    lines += [
        "",
        "## Wave trigger",
        "",
        "A role wave is triggered when a family's coverage is below the",
        "**70% binding bar** AND it has >= 4 unbound leaves in a coherent",
        "sub-cluster (role-ready). Wave briefs name the target roles from",
        "this matrix.",
        "",
        "Current wave targets (below 70% bar):",
    ]
    below = [f for f in sorted(fam)
             if fam[f]["leaves"] and fam[f]["bound"] / fam[f]["leaves"] < 0.70]
    for f in below:
        st = fam[f]
        lines.append(f"- **{f}**: {st['bound']}/{st['leaves']} "
                     f"({st['bound']/st['leaves']*100:.0f}%)")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ledger = load_ledger()
    text = render(ledger)
    if "--check" in sys.argv:
        if os.path.exists(OUT) and open(OUT).read() == text:
            print("coverage-matrix: OK (up to date)")
            return 0
        print("coverage-matrix: STALE — run without --check")
        return 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    print(f"wrote {OUT} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
